// HL7 v2.5.1 field names per segment. [name, dataType] when the type has components listed below.
export const HL7_SEGMENT_FIELDS = {
  MSH: ['Field Separator', 'Encoding Characters', ['Sending Application', 'HD'], ['Sending Facility', 'HD'],
    ['Receiving Application', 'HD'], ['Receiving Facility', 'HD'], ['Date/Time of Message', 'TS'], 'Security',
    ['Message Type', 'MSG'], 'Message Control ID', ['Processing ID', 'PT'], ['Version ID', 'VID'], 'Sequence Number',
    'Continuation Pointer', 'Accept Acknowledgment Type', 'Application Acknowledgment Type', 'Country Code',
    'Character Set', ['Principal Language of Message', 'CE'], 'Alternate Character Set Handling Scheme',
    ['Message Profile Identifier', 'EI']],
  EVN: ['Event Type Code', ['Recorded Date/Time', 'TS'], ['Date/Time Planned Event', 'TS'], 'Event Reason Code',
    ['Operator ID', 'XCN'], ['Event Occurred', 'TS'], ['Event Facility', 'HD']],
  PID: ['Set ID', ['Patient ID', 'CX'], ['Patient Identifier List', 'CX'], ['Alternate Patient ID', 'CX'],
    ['Patient Name', 'XPN'], ['Mother\'s Maiden Name', 'XPN'], ['Date/Time of Birth', 'TS'], 'Administrative Sex',
    ['Patient Alias', 'XPN'], ['Race', 'CE'], ['Patient Address', 'XAD'], 'County Code', ['Phone Number - Home', 'XTN'],
    ['Phone Number - Business', 'XTN'], ['Primary Language', 'CE'], ['Marital Status', 'CE'], ['Religion', 'CE'],
    ['Patient Account Number', 'CX'], 'SSN Number - Patient', ['Driver\'s License Number - Patient', 'DLN'],
    ['Mother\'s Identifier', 'CX'], ['Ethnic Group', 'CE'], 'Birth Place', 'Multiple Birth Indicator', 'Birth Order',
    ['Citizenship', 'CE'], ['Veterans Military Status', 'CE'], ['Nationality', 'CE'], ['Patient Death Date and Time', 'TS'],
    'Patient Death Indicator', 'Identity Unknown Indicator', 'Identity Reliability Code', ['Last Update Date/Time', 'TS'],
    ['Last Update Facility', 'HD'], ['Species Code', 'CE'], ['Breed Code', 'CE'], 'Strain', ['Production Class Code', 'CE'],
    ['Tribal Citizenship', 'CWE']],
  PD1: ['Living Dependency', 'Living Arrangement', ['Patient Primary Facility', 'XON'],
    ['Patient Primary Care Provider Name & ID No.', 'XCN'], 'Student Indicator', 'Handicap', 'Living Will Code',
    'Organ Donor Code', 'Separate Bill', ['Duplicate Patient', 'CX'], ['Publicity Code', 'CE'], 'Protection Indicator',
    'Protection Indicator Effective Date', ['Place of Worship', 'XON'], ['Advance Directive Code', 'CE'],
    'Immunization Registry Status', 'Immunization Registry Status Effective Date', 'Publicity Code Effective Date',
    'Military Branch', 'Military Rank/Grade', 'Military Status'],
  NK1: ['Set ID', ['Name', 'XPN'], ['Relationship', 'CE'], ['Address', 'XAD'], ['Phone Number', 'XTN'],
    ['Business Phone Number', 'XTN'], ['Contact Role', 'CE'], 'Start Date', 'End Date', 'Job Title', 'Job Code/Class',
    ['Employee Number', 'CX'], ['Organization Name', 'XON'], ['Marital Status', 'CE'], 'Administrative Sex',
    ['Date/Time of Birth', 'TS'], 'Living Dependency', 'Ambulatory Status', ['Citizenship', 'CE'], ['Primary Language', 'CE'],
    'Living Arrangement', ['Publicity Code', 'CE'], 'Protection Indicator', 'Student Indicator', ['Religion', 'CE'],
    ['Mother\'s Maiden Name', 'XPN'], ['Nationality', 'CE'], ['Ethnic Group', 'CE'], ['Contact Reason', 'CE'],
    ['Contact Person\'s Name', 'XPN'], ['Contact Person\'s Telephone Number', 'XTN'], ['Contact Person\'s Address', 'XAD'],
    ['Associated Party\'s Identifiers', 'CX'], 'Job Status', ['Race', 'CE'], 'Handicap',
    'Contact Person Social Security Number', 'Next of Kin Birth Place', 'VIP Indicator'],
  PV1: ['Set ID', 'Patient Class', ['Assigned Patient Location', 'PL'], 'Admission Type', ['Preadmit Number', 'CX'],
    ['Prior Patient Location', 'PL'], ['Attending Doctor', 'XCN'], ['Referring Doctor', 'XCN'], ['Consulting Doctor', 'XCN'],
    'Hospital Service', ['Temporary Location', 'PL'], 'Preadmit Test Indicator', 'Re-admission Indicator', 'Admit Source',
    'Ambulatory Status', 'VIP Indicator', ['Admitting Doctor', 'XCN'], 'Patient Type', ['Visit Number', 'CX'],
    ['Financial Class', 'FC'], 'Charge Price Indicator', 'Courtesy Code', 'Credit Rating', 'Contract Code',
    'Contract Effective Date', 'Contract Amount', 'Contract Period', 'Interest Code', 'Transfer to Bad Debt Code',
    'Transfer to Bad Debt Date', 'Bad Debt Agency Code', 'Bad Debt Transfer Amount', 'Bad Debt Recovery Amount',
    'Delete Account Indicator', 'Delete Account Date', 'Discharge Disposition', ['Discharged to Location', 'DLD'],
    ['Diet Type', 'CE'], 'Servicing Facility', 'Bed Status', 'Account Status', ['Pending Location', 'PL'],
    ['Prior Temporary Location', 'PL'], ['Admit Date/Time', 'TS'], ['Discharge Date/Time', 'TS'], 'Current Patient Balance',
    'Total Charges', 'Total Adjustments', 'Total Payments', ['Alternate Visit ID', 'CX'], 'Visit Indicator',
    ['Other Healthcare Provider', 'XCN']],
  PV2: [['Prior Pending Location', 'PL'], ['Accommodation Code', 'CE'], ['Admit Reason', 'CE'], ['Transfer Reason', 'CE'],
    'Patient Valuables', 'Patient Valuables Location', 'Visit User Code', ['Expected Admit Date/Time', 'TS'],
    ['Expected Discharge Date/Time', 'TS'], 'Estimated Length of Inpatient Stay', 'Actual Length of Inpatient Stay',
    'Visit Description', ['Referral Source Code', 'XCN'], 'Previous Service Date', 'Employment Illness Related Indicator',
    'Purge Status Code', 'Purge Status Date', 'Special Program Code', 'Retention Indicator',
    'Expected Number of Insurance Plans', 'Visit Publicity Code', 'Visit Protection Indicator',
    ['Clinic Organization Name', 'XON'], 'Patient Status Code', 'Visit Priority Code', 'Previous Treatment Date',
    'Expected Discharge Disposition', 'Signature on File Date', 'First Similar Illness Date',
    ['Patient Charge Adjustment Code', 'CE'], 'Recurring Service Code', 'Billing Media Code',
    ['Expected Surgery Date and Time', 'TS'], 'Military Partnership Code', 'Military Non-Availability Code',
    'Newborn Baby Indicator', 'Baby Detained Indicator', ['Mode of Arrival Code', 'CE'], ['Recreational Drug Use Code', 'CE'],
    ['Admission Level of Care Code', 'CE'], ['Precaution Code', 'CE'], ['Patient Condition Code', 'CE'], 'Living Will Code',
    'Organ Donor Code', ['Advance Directive Code', 'CE'], 'Patient Status Effective Date',
    ['Expected LOA Return Date/Time', 'TS'], ['Expected Pre-admission Testing Date/Time', 'TS'], 'Notify Clergy Code'],
  ORC: ['Order Control', ['Placer Order Number', 'EI'], ['Filler Order Number', 'EI'], ['Placer Group Number', 'EI'],
    'Order Status', 'Response Flag', 'Quantity/Timing', 'Parent', ['Date/Time of Transaction', 'TS'], ['Entered By', 'XCN'],
    ['Verified By', 'XCN'], ['Ordering Provider', 'XCN'], ['Enterer\'s Location', 'PL'], ['Call Back Phone Number', 'XTN'],
    ['Order Effective Date/Time', 'TS'], ['Order Control Code Reason', 'CE'], ['Entering Organization', 'CE'],
    ['Entering Device', 'CE'], ['Action By', 'XCN'], ['Advanced Beneficiary Notice Code', 'CE'],
    ['Ordering Facility Name', 'XON'], ['Ordering Facility Address', 'XAD'], ['Ordering Facility Phone Number', 'XTN'],
    ['Ordering Provider Address', 'XAD'], ['Order Status Modifier', 'CWE'],
    ['Advanced Beneficiary Notice Override Reason', 'CWE'], ['Filler\'s Expected Availability Date/Time', 'TS'],
    ['Confidentiality Code', 'CWE'], ['Order Type', 'CWE'], ['Enterer Authorization Mode', 'CNE'],
    ['Parent Universal Service Identifier', 'CWE']],
  OBR: ['Set ID', ['Placer Order Number', 'EI'], ['Filler Order Number', 'EI'], ['Universal Service Identifier', 'CE'],
    'Priority', 'Requested Date/Time', ['Observation Date/Time', 'TS'], ['Observation End Date/Time', 'TS'],
    'Collection Volume', ['Collector Identifier', 'XCN'], 'Specimen Action Code', ['Danger Code', 'CE'],
    'Relevant Clinical Information', ['Specimen Received Date/Time', 'TS'], 'Specimen Source', ['Ordering Provider', 'XCN'],
    ['Order Callback Phone Number', 'XTN'], 'Placer Field 1', 'Placer Field 2', 'Filler Field 1', 'Filler Field 2',
    ['Results Rpt/Status Chng - Date/Time', 'TS'], 'Charge to Practice', 'Diagnostic Serv Sect ID', 'Result Status',
    'Parent Result', 'Quantity/Timing', ['Result Copies To', 'XCN'], 'Parent', 'Transportation Mode',
    ['Reason for Study', 'CE'], 'Principal Result Interpreter', 'Assistant Result Interpreter', 'Technician',
    'Transcriptionist', ['Scheduled Date/Time', 'TS'], 'Number of Sample Containers',
    ['Transport Logistics of Collected Sample', 'CE'], ['Collector\'s Comment', 'CE'],
    ['Transport Arrangement Responsibility', 'CE'], 'Transport Arranged', 'Escort Required',
    ['Planned Patient Transport Comment', 'CE'], ['Procedure Code', 'CE'], ['Procedure Code Modifier', 'CE'],
    ['Placer Supplemental Service Information', 'CE'], ['Filler Supplemental Service Information', 'CE'],
    ['Medically Necessary Duplicate Procedure Reason', 'CWE'], 'Result Handling',
    ['Parent Universal Service Identifier', 'CWE']],
  OBX: ['Set ID', 'Value Type', ['Observation Identifier', 'CE'], 'Observation Sub-ID', 'Observation Value',
    ['Units', 'CE'], 'References Range', 'Abnormal Flags', 'Probability', 'Nature of Abnormal Test',
    'Observation Result Status', ['Effective Date of Reference Range', 'TS'], 'User Defined Access Checks',
    ['Date/Time of the Observation', 'TS'], ['Producer\'s ID', 'CE'], ['Responsible Observer', 'XCN'],
    ['Observation Method', 'CE'], ['Equipment Instance Identifier', 'EI'], ['Date/Time of the Analysis', 'TS'],
    'Reserved', 'Reserved', 'Reserved', ['Performing Organization Name', 'XON'],
    ['Performing Organization Address', 'XAD'], ['Performing Organization Medical Director', 'XCN']],
  NTE: ['Set ID', 'Source of Comment', 'Comment', ['Comment Type', 'CE']],
  AL1: ['Set ID', ['Allergen Type Code', 'CE'], ['Allergen Code/Mnemonic/Description', 'CE'],
    ['Allergy Severity Code', 'CE'], 'Allergy Reaction Code', 'Identification Date'],
  DG1: ['Set ID', 'Diagnosis Coding Method', ['Diagnosis Code', 'CE'], 'Diagnosis Description',
    ['Diagnosis Date/Time', 'TS'], 'Diagnosis Type', ['Major Diagnostic Category', 'CE'],
    ['Diagnostic Related Group', 'CE'], 'DRG Approval Indicator', 'DRG Grouper Review Code', ['Outlier Type', 'CE'],
    'Outlier Days', 'Outlier Cost', 'Grouper Version and Type', 'Diagnosis Priority', ['Diagnosing Clinician', 'XCN'],
    'Diagnosis Classification', 'Confidential Indicator', ['Attestation Date/Time', 'TS'], ['Diagnosis Identifier', 'EI'],
    'Diagnosis Action Code'],
  SPM: ['Set ID', ['Specimen ID', 'EIP'], 'Specimen Parent IDs', ['Specimen Type', 'CWE'],
    ['Specimen Type Modifier', 'CWE'], ['Specimen Additives', 'CWE'], ['Specimen Collection Method', 'CWE'],
    ['Specimen Source Site', 'CWE'], ['Specimen Source Site Modifier', 'CWE'], ['Specimen Collection Site', 'CWE'],
    ['Specimen Role', 'CWE'], 'Specimen Collection Amount', 'Grouped Specimen Count', 'Specimen Description',
    ['Specimen Handling Code', 'CWE'], ['Specimen Risk Code', 'CWE'], 'Specimen Collection Date/Time',
    ['Specimen Received Date/Time', 'TS'], ['Specimen Expiration Date/Time', 'TS'], 'Specimen Availability',
    ['Specimen Reject Reason', 'CWE'], ['Specimen Quality', 'CWE'], ['Specimen Appropriateness', 'CWE'],
    ['Specimen Condition', 'CWE'], 'Specimen Current Quantity', 'Number of Specimen Containers',
    ['Container Type', 'CWE'], ['Container Condition', 'CWE'], ['Specimen Child Role', 'CWE']],
  MSA: ['Acknowledgment Code', 'Message Control ID', 'Text Message', 'Expected Sequence Number',
    'Delayed Acknowledgment Type', ['Error Condition', 'CE']],
  ERR: ['Error Code and Location', 'Error Location', ['HL7 Error Code', 'CWE'], 'Severity',
    ['Application Error Code', 'CWE'], 'Application Error Parameter', 'Diagnostic Information', 'User Message',
    'Inform Person Indicator', ['Override Type', 'CWE'], ['Override Reason Code', 'CWE'],
    ['Help Desk Contact Point', 'XTN']]
}

const CE = ['Identifier', 'Text', 'Name of Coding System', 'Alternate Identifier', 'Alternate Text',
  'Name of Alternate Coding System']
const CWE = [...CE, 'Coding System Version ID', 'Alternate Coding System Version ID', 'Original Text']

// HL7 v2.5.1 component names per data type
export const HL7_DATATYPE_COMPONENTS = {
  CE, CWE, CNE: CWE,
  HD: ['Namespace ID', 'Universal ID', 'Universal ID Type'],
  TS: ['Time', 'Degree of Precision'],
  MSG: ['Message Code', 'Trigger Event', 'Message Structure'],
  PT: ['Processing ID', 'Processing Mode'],
  VID: ['Version ID', 'Internationalization Code', 'International Version ID'],
  EI: ['Entity Identifier', 'Namespace ID', 'Universal ID', 'Universal ID Type'],
  EIP: ['Placer Assigned Identifier', 'Filler Assigned Identifier'],
  FC: ['Financial Class Code', 'Effective Date'],
  DLD: ['Discharge Location', 'Effective Date'],
  DLN: ['License Number', 'Issuing State, Province, Country', 'Expiration Date'],
  CX: ['ID Number', 'Check Digit', 'Check Digit Scheme', 'Assigning Authority', 'Identifier Type Code',
    'Assigning Facility', 'Effective Date', 'Expiration Date', 'Assigning Jurisdiction', 'Assigning Agency or Department'],
  XPN: ['Family Name', 'Given Name', 'Second and Further Given Names or Initials Thereof', 'Suffix', 'Prefix', 'Degree',
    'Name Type Code', 'Name Representation Code', 'Name Context', 'Name Validity Range', 'Name Assembly Order',
    'Effective Date', 'Expiration Date', 'Professional Suffix'],
  XAD: ['Street Address', 'Other Designation', 'City', 'State or Province', 'Zip or Postal Code', 'Country',
    'Address Type', 'Other Geographic Designation', 'County/Parish Code', 'Census Tract', 'Address Representation Code',
    'Address Validity Range', 'Effective Date', 'Expiration Date'],
  XTN: ['Telephone Number', 'Telecommunication Use Code', 'Telecommunication Equipment Type', 'Email Address',
    'Country Code', 'Area/City Code', 'Local Number', 'Extension', 'Any Text', 'Extension Prefix', 'Speed Dial Code',
    'Unformatted Telephone Number'],
  XCN: ['ID Number', 'Family Name', 'Given Name', 'Second and Further Given Names or Initials Thereof', 'Suffix',
    'Prefix', 'Degree', 'Source Table', 'Assigning Authority', 'Name Type Code', 'Identifier Check Digit',
    'Check Digit Scheme', 'Identifier Type Code', 'Assigning Facility', 'Name Representation Code', 'Name Context',
    'Name Validity Range', 'Name Assembly Order', 'Effective Date', 'Expiration Date', 'Professional Suffix',
    'Assigning Jurisdiction', 'Assigning Agency or Department'],
  PL: ['Point of Care', 'Room', 'Bed', 'Facility', 'Location Status', 'Person Location Type', 'Building', 'Floor',
    'Location Description', 'Comprehensive Location Identifier', 'Assigning Authority for Location'],
  XON: ['Organization Name', 'Organization Name Type Code', 'ID Number', 'Check Digit', 'Check Digit Scheme',
    'Assigning Authority', 'Identifier Type Code', 'Assigning Facility', 'Name Representation Code',
    'Organization Identifier']
}
